log:
  level: debug
  #file: "/tmp/mosdns.txt"
#可能需要修改日志路径mosdns才能运行

data_providers:
  - tag: geosite
    file: "./rules/GeoSite.dat"
    auto_reload: true

  - tag: geoip
    file: "./rules/GeoIP.dat"
    auto_reload: true

  - tag: proxy_server
    file: "./rules/proxy_server.txt"
    auto_reload: true

  - tag: adlist
    file: "./rules/serverlist.txt"
    auto_reload: true

  - tag: whitelist
    file: "./rules/whitelist.txt"
    auto_reload: true

  - tag: hosts
    # hosts 格式
    # dns.google 8.8.8.8 8.8.4.4 2001:4860:4860::8888
    file: "./rules/hosts.txt"
    auto_reload: true

  - tag: blocklist
    file: "./rules/blocklist.txt"
    auto_reload: true

# =====================================================================================================================
plugins:
  # 缓存
  - tag: "cache"
    type: cache
    args:
      # 缓存大小，默认 1024
      size: 40960
      # 有效期 1 天
      lazy_cache_ttl: 86400
      # 如果命中过期的应答，则缓存会立即返回 TTL 为 lazy_cache_reply_ttl 的应答，然后自动在后台发送请求更新数据。
      lazy_cache_reply_ttl: 10

  # 保留应答的ip保留时间为ttl(秒)(实验性功能,可能没有效果)
  - tag: "save_reverse_lookup"
    type: reverse_lookup
    args:
      ttl: 1800
      handle_ptr: true

  # 转发至国内dns服务器的插件,请填写速度最快的dns服务器,比如运营商的dns建议使用udp协议,一两个就行不用太多
  - tag: "forward_china_dns_server"
    type: fast_forward
    args:
      upstream:
        # - addr: 223.5.5.5
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "223.5.5.5"
          enable_http3: true
        - addr: "https://doh.apad.pro/dns-query"
          dial_addr: "119.29.29.29"
          # enable_http3: true

  # 转发至海外dns服务器的插件,填写海外的dns服务器,建议使用1.1.1.1或者8.8.8.8,一两个就行,不使用代理时推荐使用tls或者https请求均可防污染防泄露(如果可以确保海外组dns可以走代理,那么用哪个协议都可以)
  - tag: "forward_clash_fake_ip"
    type: forward
    args:
      upstream:
        - addr: 127.0.0.1:1053
          # enable_pipeline: true
          #enable_pipeline为针对tcp与dns over tls的连接复用开关,可以减少握手次数降低延迟

  # 匹配国内域名的插件
  - tag: "query_is_china_domain"
    type: query_matcher
    args:
      domain:
        - "provider:geosite:cn"

  # 匹配海外常用域名的插件
  - tag: "query_is_gfw_domain"
    type: query_matcher
    args:
      domain:
        - "provider:geosite:geolocation-!cn"

  # 匹配国内 ip 的插件
  - tag: "response_has_local_ip"
    type: response_matcher
    args:
      ip:
        - "provider:geoip:cn"

  # 匹配dns泄露测试网站域名
  - tag: "query_is_dnsleak_domain"
    type: query_matcher
    args:
      domain:
        - "domain:browserleaks.org"
        - "domain:dnsleaktest.com"
        - "domain:dnsleak.asn247.net"
        - "domain:whrq.net"
        - "domain:ipleak.net"
        - "keyword:m1net.com"
        - "keyword:fast.net"
        - "keyword:ip-api.com"

  # 匹配白名单列表
  - tag: "query_is_whitelist_domain"
    type: query_matcher
    args:
      domain:
        - "provider:whitelist"

  # clash 中的 proxy server 域名
  - tag: "query_is_proxy_domain"
    type: query_matcher
    args:
      domain:
        - "provider:proxy_server"

  # 匹配黑名单列表
  - tag: "query_is_blocklist_domain"
    type: query_matcher
    args:
      domain:
        - "provider:blocklist"

  # 匹配hosts文件(这个不是系统的hosts文件,mosndns的hosts文件格式有些不一样,可以去 https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns/cha-jian-ji-qi-can-shu#hosts-yu-ming-ying-she-ip 查看)
  - tag: "query_is_hosts_domain"
    type: hosts
    args:
      hosts:
        - "provider:hosts"

  # 匹配65类型的请求
  - tag: "query_is_qtype65"
    type: query_matcher
    args:
      qtype: [65]

  # 匹配广告域名
  - tag: "query_is_ad_domain"
    type: query_matcher
    args:
      domain:
        - "provider:adlist"

  # =====================================================================================================================
  # 主要的运行逻辑插件
  # =====================================================================================================================
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义(就是上面),否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      exec:
        # 去除ecs
        - _no_ecs

        # 优化大杂烩 具体内容建议去 https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns/cha-jian-ji-qi-can-shu#miscoptm-zhuan-fa-fu-wu-qi-you-hua-da-za-hui-shi-yan-xing-v4.0+ 查看
        - _misc_optm

        # 如果匹配 则按照hosts和重定向列表的内容应答
        - query_is_hosts_domain

        # 保留ip到dns记录方便ip反查dns, 务必放在 cache 前
        # - save_reverse_lookup

        # 缓存，如果已经有其他程序开启了dns缓存则应该关闭(默认已用井号注释，如需启用请删除井号)
        #- cache

        # clash proxies 中的域名不能走 clash 的 fake-ip 模式，需要实际 ip
        - if: "query_is_proxy_domain"
          exec:
            - _prefer_ipv4
            - forward_china_dns_server
            - _return

        # 已知的非国内域名用海外dns组解析
        - if: "query_is_gfw_domain"
          exec:
            - forward_clash_fake_ip
            - _return

        # 把部分检查dns泄露的测试域名直接分流至海外dns组,看着舒服点
        # 因为网站测试用的随机生成域名很可能不在geosite数据库里,所以会使用fallback机制查询,最后导致无论如何测试都存在dns泄露的情况(实际情况是大部分的域名都已经分流)
        - if: "query_is_dnsleak_domain"
          exec:
            - forward_clash_fake_ip
            - _return

        # 将白名单列表内的域名转发到国内分组
        - if: "query_is_whitelist_domain"
          exec:
            - _prefer_ipv4
            - forward_china_dns_server
            - _return

        # 将黑名单,广告以及qtype65类型的请求屏蔽
        - if: "query_is_blocklist_domain || query_is_ad_domain || query_is_qtype65"
          exec:
            - _new_nxdomain_response
            - _return

        # 已知的国内域名用本地dns组解析
        - if: "query_is_china_domain"
          exec:
            - _prefer_ipv4
            - forward_china_dns_server #交给本地dns组处理
            - _return

        # 剩下的，全部到 clash fake ip
        - forward_clash_fake_ip

# =====================================================================================================================
#                       server
# =====================================================================================================================
servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: ":1153"
      - protocol: tcp
        addr: ":1153"
    #mosdns监听的协议,地址和端口,可以有多个 默认监听5301端口
